-- MySQL Script generated by MySQL Workbench
-- Wed Jul  3 13:27:13 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema super_weapon
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema super_weapon
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `super_weapon` DEFAULT CHARACTER SET utf8 ;
USE `super_weapon` ;

-- -----------------------------------------------------
-- Table `super_weapon`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `super_weapon`.`user` (
  `username` VARCHAR(128) NOT NULL,
  `password` VARCHAR(128) NOT NULL,
  `register_time` VARCHAR(128) NOT NULL,
  `random` VARCHAR(128) NOT NULL,
  `sex` BINARY(1) NULL DEFAULT 1,
  `born_country` TEXT NULL,
  `serving_country` TEXT NULL COMMENT 'The countries which commanders are serving for.',
  `born_time` DATETIME NULL,
  `battle_loss_ratio` DOUBLE NULL,
  `crew_number` INT NULL,
  `message` INT NULL,
  `balance` INT NULL DEFAULT 0,
  PRIMARY KEY (`username`));


-- -----------------------------------------------------
-- Table `super_weapon`.`starship`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `super_weapon`.`starship` (
  `id` INT NOT NULL,
  `name` VARCHAR(128) NULL,
  `product_country` VARCHAR(128) NULL,
  `duty_officer` VARCHAR(128) NULL,
  `product_date` VARCHAR(128) NULL,
  `valuation` INT NULL DEFAULT 0,
  `status` INT NULL,
  `activity` INT NULL,
  `verified` BIT(1) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `super_weapon`.`user_has_starship`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `super_weapon`.`user_has_starship` (
  `user_username` VARCHAR(128) NOT NULL,
  `starship_id` INT NOT NULL,
  PRIMARY KEY (`user_username`, `starship_id`),
  INDEX `fk_user_has_starship_starship1_idx` (`starship_id` ASC),
  INDEX `fk_user_has_starship_user_idx` (`user_username` ASC),
  CONSTRAINT `fk_user_has_starship_user`
    FOREIGN KEY (`user_username`)
    REFERENCES `super_weapon`.`user` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_starship_starship1`
    FOREIGN KEY (`starship_id`)
    REFERENCES `super_weapon`.`starship` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `super_weapon`.`weapon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `super_weapon`.`weapon` (
  `code` INT NOT NULL,
  `name` VARCHAR(128) NULL,
  `image` VARCHAR(1024) NULL,
  `price` INT NULL,
  `category` INT NULL,
  `reviews` INT NULL,
  `status` INT NULL,
  PRIMARY KEY (`code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `super_weapon`.`starship_has_weapon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `super_weapon`.`starship_has_weapon` (
  `starship_id` INT NOT NULL,
  `weapon_code` INT NOT NULL,
  PRIMARY KEY (`starship_id`, `weapon_code`),
  INDEX `fk_starship_has_weapon_weapon1_idx` (`weapon_code` ASC),
  INDEX `fk_starship_has_weapon_starship1_idx` (`starship_id` ASC),
  CONSTRAINT `fk_starship_has_weapon_starship1`
    FOREIGN KEY (`starship_id`)
    REFERENCES `super_weapon`.`starship` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_starship_has_weapon_weapon1`
    FOREIGN KEY (`weapon_code`)
    REFERENCES `super_weapon`.`weapon` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `super_weapon`.`user_has_starship_has_weapon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `super_weapon`.`user_has_starship_has_weapon` (
  `user_username` VARCHAR(128) NOT NULL,
  `starship_has_weapon_starship_id` INT NOT NULL,
  `starship_has_weapon_weapon_code` INT NOT NULL,
  PRIMARY KEY (`user_username`, `starship_has_weapon_starship_id`, `starship_has_weapon_weapon_code`),
  INDEX `fk_user_has_starship_has_weapon_starship_has_weapon1_idx` (`starship_has_weapon_starship_id` ASC, `starship_has_weapon_weapon_code` ASC),
  INDEX `fk_user_has_starship_has_weapon_user1_idx` (`user_username` ASC),
  CONSTRAINT `fk_user_has_starship_has_weapon_user1`
    FOREIGN KEY (`user_username`)
    REFERENCES `super_weapon`.`user` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_starship_has_weapon_starship_has_weapon1`
    FOREIGN KEY (`starship_has_weapon_starship_id` , `starship_has_weapon_weapon_code`)
    REFERENCES `super_weapon`.`starship_has_weapon` (`starship_id` , `weapon_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
